[package]
name = "javafx-from-rust"
version = "0.2.0"
authors = ["astonbitecode"]
edition = "2018"

[dependencies]
j4rs = {git = "https://github.com/astonbitecode/j4rs.git"}

[build-dependencies]
j4rs = {git = "https://github.com/astonbitecode/j4rs.git"}